// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;
using namespace arma;
using namespace std;

// dist2
double dist2(double lat1, double long1, double lat2, double long2);
RcppExport SEXP _GPvecchia_dist2(SEXP lat1SEXP, SEXP long1SEXP, SEXP lat2SEXP, SEXP long2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type long1(long1SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< double >::type long2(long2SEXP);
    rcpp_result_gen = Rcpp::wrap(dist2(lat1, long1, lat2, long2));
    return rcpp_result_gen;
END_RCPP
}
// dist1
double dist1(double x, double y);
RcppExport SEXP _GPvecchia_dist1(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dist1(x, y));
    return rcpp_result_gen;
END_RCPP
}
// calcPWD2
mat calcPWD2(mat x);
RcppExport SEXP _GPvecchia_calcPWD2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(calcPWD2(x));
    return rcpp_result_gen;
END_RCPP
}
// calcPWD1
mat calcPWD1(vec x);
RcppExport SEXP _GPvecchia_calcPWD1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(calcPWD1(x));
    return rcpp_result_gen;
END_RCPP
}
// NZentries_new2
List NZentries_new2(int Ncores, int n, const mat& locs, const umat& revNNarray, const mat& revCondOnLatent, const vec& nuggets, const vec covparms);
RcppExport SEXP _GPvecchia_NZentries_new2(SEXP NcoresSEXP, SEXP nSEXP, SEXP locsSEXP, SEXP revNNarraySEXP, SEXP revCondOnLatentSEXP, SEXP nuggetsSEXP, SEXP covparmsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Ncores(NcoresSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const mat& >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< const umat& >::type revNNarray(revNNarraySEXP);
    Rcpp::traits::input_parameter< const mat& >::type revCondOnLatent(revCondOnLatentSEXP);
    Rcpp::traits::input_parameter< const vec& >::type nuggets(nuggetsSEXP);
    Rcpp::traits::input_parameter< const vec >::type covparms(covparmsSEXP);
    rcpp_result_gen = Rcpp::wrap(NZentries_new2(Ncores, n, locs, revNNarray, revCondOnLatent, nuggets, covparms));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GPvecchia_dist2", (DL_FUNC) &_GPvecchia_dist2, 4},
    {"_GPvecchia_dist1", (DL_FUNC) &_GPvecchia_dist1, 2},
    {"_GPvecchia_calcPWD2", (DL_FUNC) &_GPvecchia_calcPWD2, 1},
    {"_GPvecchia_calcPWD1", (DL_FUNC) &_GPvecchia_calcPWD1, 1},
    {"_GPvecchia_NZentries_new2", (DL_FUNC) &_GPvecchia_NZentries_new2, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_GPvecchia(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
