# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist2 <- function(lat1, long1, lat2, long2) {
    .Call('_GPvecchia_dist2', PACKAGE = 'GPvecchia', lat1, long1, lat2, long2)
}

dist1 <- function(x, y) {
    .Call('_GPvecchia_dist1', PACKAGE = 'GPvecchia', x, y)
}

calcPWD2 <- function(x) {
    .Call('_GPvecchia_calcPWD2', PACKAGE = 'GPvecchia', x)
}

calcPWD1 <- function(x) {
    .Call('_GPvecchia_calcPWD1', PACKAGE = 'GPvecchia', x)
}

MaternFun <- function(distmat, covparms) {
    .Call('_GPvecchia_MaternFun', PACKAGE = 'GPvecchia', distmat, covparms)
}

U_NZentries <- function(Ncores, n, locs, revNNarray, revCondOnLatent, nuggets, covparms) {
    .Call('_GPvecchia_U_NZentries', PACKAGE = 'GPvecchia', Ncores, n, locs, revNNarray, revCondOnLatent, nuggets, covparms)
}

