# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Matern covariance function
#'
#' @param distmat A matrix with distances between points
#' @param covparms A vector with parameters (marg. variance, range, smoothness)
#' @export
MaternFun <- function(distmat, covparms) {
    .Call('_GPvecchia_MaternFun', PACKAGE = 'GPvecchia', distmat, covparms)
}

MaxMincpp <- function(locations) {
    .Call('_GPvecchia_MaxMincpp', PACKAGE = 'GPvecchia', locations)
}

EsqeFun <- function(distmat, covparms) {
    .Call('_GPvecchia_EsqeFun', PACKAGE = 'GPvecchia', distmat, covparms)
}

U_NZentries_mat <- function(Ncores, n, locs, revNNarray, revCondOnLatent, nuggets, nuggets_obsord, COV, covparms) {
    .Call('_GPvecchia_U_NZentries_mat', PACKAGE = 'GPvecchia', Ncores, n, locs, revNNarray, revCondOnLatent, nuggets, nuggets_obsord, COV, covparms)
}

U_NZentries <- function(Ncores, n, locs, revNNarray, revCondOnLatent, nuggets, nuggets_obsord, COV, covparms) {
    .Call('_GPvecchia_U_NZentries', PACKAGE = 'GPvecchia', Ncores, n, locs, revNNarray, revCondOnLatent, nuggets, nuggets_obsord, COV, covparms)
}

createUcppM <- function(ptrs, inds, cov_vals) {
    .Call('_GPvecchia_createUcppM', PACKAGE = 'GPvecchia', ptrs, inds, cov_vals)
}

createUcpp <- function(ptrs, inds, locsord, covparams) {
    .Call('_GPvecchia_createUcpp', PACKAGE = 'GPvecchia', ptrs, inds, locsord, covparams)
}

generateNNarray <- function(locs, J, M, r, m) {
    .Call('_GPvecchia_generateNNarray', PACKAGE = 'GPvecchia', locs, J, M, r, m)
}

