#' evaluation of the likelihood
#'
#' @param vecchia.approx: a vecchia object as generated by vecchia_specify()
#' @param covparms: covariance parameters as a vector
#' @param nuggets: either a single (constant) nugget or a vector of nugget terms for the observations
#' @param covmodel: covariance model, 'matern' by default
#'
#' @return (multivariate normal) loglikelihood implied by the Vecchia approximation
#' @examples
#' z=rnorm(5); locs=matrix(1:5,ncol=1); vecchia.approx=vecchia_specify(locs,m=5)
#' vecchia_likelihood(z,vecchia.approx,covparms=c(1,2,.5),nuggets=.2)
#' @export

##  evaluation of the likelihood

vecchia_likelihood=function(z,vecchia.approx,covparms,nuggets,covmodel='matern') {

  # create the U matrix
  U.obj=createU(vecchia.approx,covparms,nuggets,covmodel)

  # remove NAs in data and U
  na.rm()

  # compute the loglikelihood
  vecchia_likelihood_U(z,U.obj)
}



## remove missing data (NA)
na.rm=function(){ # overwrites z and U.obj
  if(any(is.na(z))){
    ind.na=(((1:nrow(U.obj$U))[!U.obj$latent])[U.obj$ord.z])[is.na(z)]
    if(any(apply(U.obj$U[,ind.na,drop=FALSE],2,nnzero)>2)) stop(
      'NA data is conditioned upon')
    U.obj$U <<- U.obj$U[-ind.na,-ind.na]
    U.obj$latent <<- U.obj$latent[-ind.na]
    U.obj$ord.z <<- order(order(U.obj$ord.z[U.obj$ord.z %in% which(!is.na(z))]))
    z <<- z[!is.na(z)]
  }
}


## evaluate vecchia likelihood based on U

vecchia_likelihood_U=function(z,U.obj) {
  ### output: loglikelihood (for z)

  U=U.obj$U
  latent=U.obj$latent
  zord=z[U.obj$ord.z]

  # constant
  const=sum(!latent)*log(2*pi)

  # numerator
  z1=Matrix::crossprod(U[!latent,],zord)
  quadform.num=sum(z1^2)
  logdet.num=-2*sum(log(Matrix::diag(U)))

  # denominator
  U.y=U[latent,]
  z2=as.numeric(U.y%*%z1)
  V.ord=U2V(U.obj)
  z3=solve(V.ord,rev(z2),system='L')
  quadform.denom=sum(z3^2)
  logdet.denom=-2*sum(log(diag(V.ord)))

  # putting everything together
  neg2loglik=logdet.num-logdet.denom+quadform.num-quadform.denom+const
  loglik=-neg2loglik/2
  return(loglik)

}


## function to reverse-order a matrix
rev.mat=function(mat) mat[nrow(mat):1,ncol(mat):1,drop=FALSE]
